"""
Wedding Moment Nepal — Security Audit Report (PDF)
Generated by ReportLab. Output: /home/z/my-project/download/Wedding_Moment_Nepal_Security_Audit.pdf
"""
import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
from reportlab.platypus import (
    BaseDocTemplate, PageTemplate, Frame, NextPageTemplate, PageBreak,
    Paragraph, Spacer, Table, TableStyle, KeepTogether, Image, ListFlowable,
    ListItem, HRFlowable,
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfgen import canvas

# ============================================================
# Font registration
# ============================================================
FONT_DIR = "/usr/share/fonts"
pdfmetrics.registerFont(TTFont("NotoSerifSC", f"{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf"))
pdfmetrics.registerFont(TTFont("NotoSerifSC-Bold", f"{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf"))
pdfmetrics.registerFont(TTFont("LibMono", f"{FONT_DIR}/truetype/liberation/LiberationMono-Regular.ttf"))
pdfmetrics.registerFont(TTFont("LibMono-Bold", f"{FONT_DIR}/truetype/liberation/LiberationMono-Bold.ttf"))
pdfmetrics.registerFont(TTFont("LibSans", f"{FONT_DIR}/truetype/liberation/LiberationSans-Regular.ttf"))
pdfmetrics.registerFont(TTFont("LibSans-Bold", f"{FONT_DIR}/truetype/liberation/LiberationSans-Bold.ttf"))
registerFontFamily("NotoSerifSC", normal="NotoSerifSC", bold="NotoSerifSC-Bold")
registerFontFamily("LibSans", normal="LibSans", bold="LibSans-Bold")
registerFontFamily("LibMono", normal="LibMono", bold="LibMono-Bold")

# ============================================================
# Palette — Security Audit Dark
# ============================================================
C_PRIMARY = colors.HexColor("#0F172A")   # near-black navy
C_ACCENT = colors.HexColor("#DC2626")    # alert red
C_CRITICAL = colors.HexColor("#B91C1C")
C_HIGH = colors.HexColor("#EA580C")
C_MEDIUM = colors.HexColor("#CA8A04")
C_LOW = colors.HexColor("#0891B2")
C_INFO = colors.HexColor("#475569")
C_BG_LIGHT = colors.HexColor("#F8FAFC")
C_BG_CODE = colors.HexColor("#F1F5F9")
C_BORDER = colors.HexColor("#CBD5E1")
C_TEXT = colors.HexColor("#1E293B")
C_MUTED = colors.HexColor("#64748B")
C_GOLD = colors.HexColor("#B8860B")
C_SUCCESS = colors.HexColor("#15803D")

# ============================================================
# Styles
# ============================================================
styles = getSampleStyleSheet()

S_COVER_TITLE = ParagraphStyle("CoverTitle", parent=styles["Title"],
    fontName="NotoSerifSC-Bold", fontSize=36, leading=44, textColor=colors.white,
    alignment=TA_LEFT, spaceAfter=12)
S_COVER_SUB = ParagraphStyle("CoverSub", parent=styles["Normal"],
    fontName="NotoSerifSC", fontSize=16, leading=22, textColor=colors.HexColor("#E2E8F0"),
    alignment=TA_LEFT, spaceAfter=8)
S_COVER_META = ParagraphStyle("CoverMeta", parent=styles["Normal"],
    fontName="LibSans", fontSize=10, leading=14, textColor=colors.HexColor("#94A3B8"),
    alignment=TA_LEFT)
S_COVER_TAG = ParagraphStyle("CoverTag", parent=styles["Normal"],
    fontName="LibSans-Bold", fontSize=9, leading=12, textColor=colors.white,
    alignment=TA_CENTER)

S_H1 = ParagraphStyle("H1", parent=styles["Heading1"],
    fontName="NotoSerifSC-Bold", fontSize=22, leading=28, textColor=C_PRIMARY,
    spaceBefore=18, spaceAfter=10, alignment=TA_LEFT, keepWithNext=True)
S_H2 = ParagraphStyle("H2", parent=styles["Heading2"],
    fontName="NotoSerifSC-Bold", fontSize=15, leading=20, textColor=C_PRIMARY,
    spaceBefore=14, spaceAfter=6, alignment=TA_LEFT, keepWithNext=True)
S_H3 = ParagraphStyle("H3", parent=styles["Heading3"],
    fontName="LibSans-Bold", fontSize=12, leading=16, textColor=C_PRIMARY,
    spaceBefore=10, spaceAfter=4, alignment=TA_LEFT, keepWithNext=True)

S_BODY = ParagraphStyle("Body", parent=styles["Normal"],
    fontName="NotoSerifSC", fontSize=10.5, leading=15, textColor=C_TEXT,
    alignment=TA_JUSTIFY, spaceAfter=6, firstLineIndent=0)
S_BODY_TIGHT = ParagraphStyle("BodyTight", parent=S_BODY, spaceAfter=2)
S_BULLET = ParagraphStyle("Bullet", parent=S_BODY, leftIndent=14, bulletIndent=0, spaceAfter=3)
S_MUTED = ParagraphStyle("Muted", parent=S_BODY, textColor=C_MUTED, fontSize=9.5, leading=13)
S_CAPTION = ParagraphStyle("Caption", parent=S_MUTED, alignment=TA_CENTER, fontSize=9, leading=12)

S_CODE = ParagraphStyle("Code", parent=styles["Code"],
    fontName="LibMono", fontSize=8.5, leading=11.5, textColor=C_TEXT,
    backColor=C_BG_CODE, borderPadding=(6, 6, 6, 6),
    leftIndent=8, rightIndent=8, spaceBefore=4, spaceAfter=8,
    borderColor=C_BORDER, borderWidth=0.5)

S_TABLE_HEADER = ParagraphStyle("TableHeader", parent=styles["Normal"],
    fontName="LibSans-Bold", fontSize=9, leading=12, textColor=colors.white,
    alignment=TA_LEFT)
S_TABLE_CELL = ParagraphStyle("TableCell", parent=styles["Normal"],
    fontName="NotoSerifSC", fontSize=9, leading=12, textColor=C_TEXT,
    alignment=TA_LEFT)
S_TABLE_CELL_MONO = ParagraphStyle("TableCellMono", parent=S_TABLE_CELL,
    fontName="LibMono", fontSize=8, leading=11)

S_FINDING_TITLE = ParagraphStyle("FindingTitle", parent=S_H3,
    fontSize=13, leading=17, textColor=C_PRIMARY, spaceBefore=14, spaceAfter=2)
S_FINDING_META = ParagraphStyle("FindingMeta", parent=S_MUTED,
    fontName="LibMono", fontSize=8.5, leading=11, spaceAfter=4)
S_FINDING_LABEL = ParagraphStyle("FindingLabel", parent=styles["Normal"],
    fontName="LibSans-Bold", fontSize=9, leading=12, textColor=C_PRIMARY,
    spaceBefore=4, spaceAfter=2)
S_FINDING_BODY = ParagraphStyle("FindingBody", parent=S_BODY, spaceAfter=4)

# ============================================================
# Helper builders
# ============================================================
def p(text, style=S_BODY):
    return Paragraph(text, style)

def code_block(text):
    """Render a code block, preserving whitespace via <br/> and &nbsp;."""
    escaped = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    escaped = escaped.replace(" ", "&nbsp;").replace("\n", "<br/>")
    return Paragraph(escaped, S_CODE)

def severity_badge(level):
    color_map = {
        "CRITICAL": (C_CRITICAL, "CRITICAL"),
        "HIGH": (C_HIGH, "HIGH"),
        "MEDIUM": (C_MEDIUM, "MEDIUM"),
        "LOW": (C_LOW, "LOW"),
        "INFO": (C_INFO, "INFO"),
    }
    bg, label = color_map[level.upper()]
    t = Table([[Paragraph(f'<font color="white"><b>{label}</b></font>', S_COVER_TAG)]],
              colWidths=[60], rowHeights=[14])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,-1), bg),
        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
        ("LEFTPADDING", (0,0), (-1,-1), 4),
        ("RIGHTPADDING", (0,0), (-1,-1), 4),
        ("TOPPADDING", (0,0), (-1,-1), 1),
        ("BOTTOMPADDING", (0,0), (-1,-1), 1),
    ]))
    return t

def finding_block(finding_id, severity, title, file_line, whats_wrong, why_matters, fix_code=None, fix_text=None):
    """Build a complete finding block as a list of flowables (kept together when small)."""
    elems = []
    # Title row: badge + finding ID + title
    title_table = Table([[
        severity_badge(severity),
        Paragraph(f'<b>{finding_id}.</b> {title}', S_FINDING_TITLE)
    ]], colWidths=[70, 110])
    title_table.setStyle(TableStyle([
        ("VALIGN", (0,0), (-1,-1), "TOP"),
        ("LEFTPADDING", (0,0), (-1,-1), 0),
        ("RIGHTPADDING", (0,0), (-1,-1), 0),
        ("TOPPADDING", (0,0), (-1,-1), 0),
        ("BOTTOMPADDING", (0,0), (-1,-1), 0),
    ]))
    elems.append(title_table)
    elems.append(Paragraph(f'<font name="LibMono" size="8.5" color="#64748B">{file_line}</font>', S_FINDING_META))
    elems.append(Paragraph("<b>What's wrong</b>", S_FINDING_LABEL))
    elems.append(Paragraph(whats_wrong, S_FINDING_BODY))
    elems.append(Paragraph("<b>Why it matters</b>", S_FINDING_LABEL))
    elems.append(Paragraph(why_matters, S_FINDING_BODY))
    if fix_text:
        elems.append(Paragraph("<b>Suggested fix</b>", S_FINDING_LABEL))
        elems.append(Paragraph(fix_text, S_FINDING_BODY))
    if fix_code:
        elems.append(Paragraph("<b>Suggested fix (code)</b>", S_FINDING_LABEL))
        elems.append(code_block(fix_code))
    elems.append(Spacer(1, 6))
    return elems

def make_table(header, rows, col_widths=None, header_bg=C_PRIMARY, zebra=True):
    """Build a styled table. header and rows are lists of strings (or Paragraphs)."""
    data = []
    hdr_row = [Paragraph(h, S_TABLE_HEADER) for h in header]
    data.append(hdr_row)
    for row in rows:
        new_row = []
        for cell in row:
            if isinstance(cell, str):
                new_row.append(Paragraph(cell, S_TABLE_CELL))
            else:
                new_row.append(cell)
        data.append(new_row)

    t = Table(data, colWidths=col_widths, repeatRows=1)
    style = [
        ("BACKGROUND", (0,0), (-1,0), header_bg),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("VALIGN", (0,0), (-1,-1), "TOP"),
        ("LEFTPADDING", (0,0), (-1,-1), 6),
        ("RIGHTPADDING", (0,0), (-1,-1), 6),
        ("TOPPADDING", (0,0), (-1,-1), 5),
        ("BOTTOMPADDING", (0,0), (-1,-1), 5),
        ("LINEBELOW", (0,0), (-1,0), 0.5, C_PRIMARY),
        ("LINEBELOW", (0,1), (-1,-1), 0.25, C_BORDER),
        ("BOX", (0,0), (-1,-1), 0.5, C_BORDER),
    ]
    if zebra:
        for i in range(1, len(data)):
            if i % 2 == 0:
                style.append(("BACKGROUND", (0,i), (-1,i), C_BG_LIGHT))
    t.setStyle(TableStyle(style))
    return t

def hr(color=C_BORDER, thickness=0.5, space=4):
    return HRFlowable(width="100%", thickness=thickness, color=color,
                      spaceBefore=space, spaceAfter=space)

# ============================================================
# Cover page (drawn directly on canvas)
# ============================================================
def draw_cover(canv, doc):
    """Draw the cover page directly on the canvas."""
    w, h = A4
    # Dark navy background
    canv.setFillColor(C_PRIMARY)
    canv.rect(0, 0, w, h, fill=1, stroke=0)
    # Red accent stripe (vertical, left)
    canv.setFillColor(C_ACCENT)
    canv.rect(0, 0, 8*mm, h, fill=1, stroke=0)
    # Gold thin line below title area
    canv.setStrokeColor(C_GOLD)
    canv.setLineWidth(0.8)
    canv.line(25*mm, h - 110*mm, 100*mm, h - 110*mm)

    # Eyebrow label
    canv.setFillColor(colors.HexColor("#94A3B8"))
    canv.setFont("LibSans-Bold", 9)
    canv.drawString(25*mm, h - 35*mm, "SECURITY AUDIT REPORT")

    # Title
    canv.setFillColor(colors.white)
    canv.setFont("NotoSerifSC-Bold", 34)
    canv.drawString(25*mm, h - 55*mm, "Wedding Moment Nepal")
    canv.setFont("NotoSerifSC", 18)
    canv.setFillColor(colors.HexColor("#E2E8F0"))
    canv.drawString(25*mm, h - 70*mm, "Next.js 16 Storefront — Hardening Review")

    # Subtitle / tagline
    canv.setFont("NotoSerifSC", 11)
    canv.setFillColor(colors.HexColor("#CBD5E1"))
    canv.drawString(25*mm, h - 82*mm, "Code-level audit + deployment hardening plan")

    # Severity bar
    y = h - 130*mm
    canv.setFillColor(C_CRITICAL)
    canv.rect(25*mm, y, 18*mm, 8*mm, fill=1, stroke=0)
    canv.setFillColor(colors.white)
    canv.setFont("LibSans-Bold", 10)
    canv.drawCentredString(34*mm, y + 2.5*mm, "8 CRITICAL")
    canv.setFillColor(C_HIGH)
    canv.rect(46*mm, y, 18*mm, 8*mm, fill=1, stroke=0)
    canv.drawCentredString(55*mm, y + 2.5*mm, "9 HIGH")
    canv.setFillColor(C_MEDIUM)
    canv.rect(67*mm, y, 22*mm, 8*mm, fill=1, stroke=0)
    canv.drawCentredString(78*mm, y + 2.5*mm, "14 MEDIUM")
    canv.setFillColor(C_LOW)
    canv.rect(92*mm, y, 18*mm, 8*mm, fill=1, stroke=0)
    canv.drawCentredString(101*mm, y + 2.5*mm, "19 LOW")

    # Verdict block
    canv.setFillColor(colors.HexColor("#1E293B"))
    canv.rect(25*mm, h - 175*mm, 160*mm, 30*mm, fill=1, stroke=0)
    canv.setStrokeColor(C_ACCENT)
    canv.setLineWidth(1.5)
    canv.line(25*mm, h - 145*mm, 25*mm, h - 175*mm)
    canv.setFillColor(C_ACCENT)
    canv.setFont("LibSans-Bold", 10)
    canv.drawString(32*mm, h - 152*mm, "VERDICT")
    canv.setFillColor(colors.white)
    canv.setFont("NotoSerifSC-Bold", 13)
    canv.drawString(32*mm, h - 162*mm, "Do not deploy to production until all 8 Critical")
    canv.drawString(32*mm, h - 170*mm, "findings are closed and re-verified.")

    # Footer meta
    canv.setFillColor(colors.HexColor("#64748B"))
    canv.setFont("LibSans", 9)
    canv.drawString(25*mm, 25*mm, "Prepared by  Z.ai Security Review")
    canv.drawString(25*mm, 19*mm, "Report date   2026-07-27")
    canv.drawString(25*mm, 13*mm, "Classification  Confidential — Studio Owner Use Only")
    # Version
    canv.drawRightString(w - 25*mm, 25*mm, "Version 1.0")
    canv.drawRightString(w - 25*mm, 19*mm, "Audit scope: 50 findings")
    canv.drawRightString(w - 25*mm, 13*mm, "Document ID  WMN-SEC-001")

# ============================================================
# Body page template (header + footer)
# ============================================================
def draw_body_page(canv, doc):
    """Header and footer for body pages."""
    w, h = A4
    # Header line
    canv.setStrokeColor(C_BORDER)
    canv.setLineWidth(0.4)
    canv.line(20*mm, h - 18*mm, w - 20*mm, h - 18*mm)
    canv.setFont("LibSans", 8.5)
    canv.setFillColor(C_MUTED)
    canv.drawString(20*mm, h - 14*mm, "Wedding Moment Nepal  ·  Security Audit Report")
    canv.drawRightString(w - 20*mm, h - 14*mm, "Confidential")
    # Footer
    canv.line(20*mm, 16*mm, w - 20*mm, 16*mm)
    canv.setFillColor(C_MUTED)
    canv.drawString(20*mm, 11*mm, "Z.ai Security Review  ·  2026-07-27")
    canv.drawRightString(w - 20*mm, 11*mm, f"Page {doc.page - 1}")
    # Red accent dot in footer
    canv.setFillColor(C_ACCENT)
    canv.circle(w/2, 12.5*mm, 1.0, fill=1, stroke=0)

# ============================================================
# Build the story
# ============================================================
story = []

# Cover page is drawn directly — just need a page break
story.append(NextPageTemplate("body"))
story.append(PageBreak())

# ---------------- Section 2: Executive Summary ----------------
story.append(p("1. Executive Summary", S_H1))
story.append(hr(C_ACCENT, 1.0, 2))
story.append(p(
    "The Wedding Moment Nepal storefront is a custom Next.js 16 application that handles customer "
    "personally identifiable information (PII) — names, email addresses, phone numbers, wedding dates — "
    "and processes payment initiation through the eSewa and Khalti Nepali payment gateways. A static "
    "code review of the entire <font name='LibMono'>src/</font> tree, the Prisma schema, the deployment "
    "scripts, and the Caddy reverse proxy configuration has identified <b>50 security findings</b>: "
    "8 Critical, 9 High, 14 Medium, and 19 Low / Informational. Several of these issues are individually "
    "critical; together they constitute a systemic security failure that would block any responsible "
    "production deployment."
))
story.append(p(
    "The most urgent findings are: (1) the production Caddyfile contains an unauthenticated reverse-proxy "
    "vulnerability that allows any external attacker to probe arbitrary localhost ports on the server "
    "(<b>C-8</b>); (2) the <font name='LibMono'>GET /api/bookings</font> endpoint has no authentication "
    "and returns the 50 most recent customer bookings — including PII — to any anonymous caller "
    "(<b>C-1</b>); (3) the SQLite database and the <font name='LibMono'>.env</font> file are both "
    "committed to git history with real customer data and configuration (<b>C-5, C-6</b>); (4) the "
    "build script copies the development database verbatim into the production tarball (<b>C-7</b>); "
    "and (5) when the eSewa or Khalti secret keys are unset, the application silently enters a "
    "<i>demo mode</i> that marks orders as paid without any actual payment occurring (<b>C-3</b>)."
))
story.append(p(
    "Beyond the Critical tier, the application lacks every baseline control expected of a payment-"
    "handling web app: no input validation framework (Zod is installed but unused), no rate limiting "
    "on any endpoint, no CSRF protection, no Content-Security-Policy or other security headers, no "
    "authentication system (the <font name='LibMono'>next-auth</font> dependency is declared but never "
    "wired up), no audit log table, and no payment callback routes — meaning that even after a customer "
    "pays, the order row is never updated from <i>initiated</i> to <i>paid</i>, because the callback "
    "URLs configured in the eSewa/Khalti initiate requests simply return a 404."
))
story.append(p(
    "<b>Verdict.</b> Do not deploy this build to a production environment. The recommended path is to "
    "complete Tier 1 of the remediation roadmap in this report (approximately 4 hours of work) before "
    "any further production activity, then proceed through Tier 2 and Tier 3 in the following two weeks. "
    "Section 11 of this report contains a written incident-response plan that should be operational "
    "before the site accepts real customer payments."
))

# ---------------- Section 3: Scope & Methodology ----------------
story.append(p("2. Scope & Methodology", S_H1))
story.append(hr(C_ACCENT, 1.0, 2))
story.append(p(
    "<b>In scope.</b> Every source file under <font name='LibMono'>src/</font> (API routes, components, "
    "library code, configuration), the Prisma schema at <font name='LibMono'>prisma/schema.prisma</font>, "
    "the public assets directory, and all root-level configuration files including <font name='LibMono'>"
    "next.config.ts</font>, <font name='LibMono'>Caddyfile</font>, <font name='LibMono'>package.json</font>, "
    "<font name='LibMono'>.env</font>, and the build/start scripts under <font name='LibMono'>.zscripts/</font>. "
    "Dependencies declared in <font name='LibMono'>package.json</font> were checked against current "
    "advisory databases for known vulnerabilities."
))
story.append(p(
    "<b>Out of scope.</b> The runtime container, the network layer beyond the Caddyfile, the CI/CD "
    "pipeline (none exists at present), and the external eSewa and Khalti servers themselves. The "
    "reviewer did not perform dynamic penetration testing, fuzzing, or runtime exploit verification — "
    "all findings are derived from static analysis of the code as committed at <font name='LibMono'>"
    "7c7ffec</font> on the project's main branch."
))
story.append(p(
    "<b>Methodology.</b> Each file was read in full. API routes were assessed against the OWASP API "
    "Security Top 10 (2023). Payment flows were compared against the official eSewa v2 and Khalti v2 "
    "integration specifications. Configuration files were checked against the Next.js and Caddy "
    "hardening guides. Findings were graded on a five-level severity scale (Critical / High / Medium "
    "/ Low / Informational) based on exploitability, blast radius, and the sensitivity of the data "
    "at risk. Every finding references its exact file path and line number to enable rapid remediation."
))
story.append(p(
    "<b>Stack translation note.</b> The user's original request asked for a Shopify/WooCommerce "
    "security review. The actual application is neither — it is a custom Next.js storefront. The "
    "10 original checklist items have been translated to fit the real stack, and Appendix A provides "
    "the inverse mapping (each Next.js finding → what it would correspond to on Shopify/WooCommerce) "
    "in case the studio ever migrates platforms."
))

# ---------------- Section 4: Stack Overview ----------------
story.append(p("3. Stack Overview", S_H1))
story.append(hr(C_ACCENT, 1.0, 2))
story.append(p(
    "The audited application is built on Next.js 16.1.1 with the App Router, using Turbopack as the "
    "bundler and <font name='LibMono'>output: \"standalone\"</font> for production builds. The "
    "database is SQLite, accessed through Prisma ORM 6.11.1, with the database file persisted at "
    "<font name='LibMono'>db/custom.db</font> inside the project root. Payment integration uses the "
    "eSewa v2 HMAC-SHA256 signed flow and the Khalti v2 server-to-server ePayment initiation API. "
    "The production runtime is Bun (not Node.js), fronted by a Caddy 2 reverse proxy listening on "
    "port 81. The frontend uses Tailwind CSS 4 with the shadcn/ui component library, next-themes for "
    "dark mode, and Google Fonts (Montserrat body, Playfair Display headings)."
))
story.append(p(
    "The deployment model is unusual: the build script (<font name='LibMono'>.zscripts/build.sh</font>) "
    "produces a tarball that contains the standalone Next.js server, a copy of the development SQLite "
    "database, the Caddyfile, and a start script. This tarball is uploaded to the hosting environment "
    "and started with <font name='LibMono'>caddy run</font> as PID 1, which in turn spawns "
    "<font name='LibMono'>bun server.js</font> as a child process. There is no Dockerfile, no "
    "infrastructure-as-code, no CI/CD pipeline, and no automated backup mechanism — the SQLite file "
    "lives in the container filesystem and is lost if the container is recreated."
))

# ---------------- Section 5: 10-Point Checklist Mapping ----------------
story.append(p("4. Original 10-Point Checklist — Translated to Actual Stack", S_H1))
story.append(hr(C_ACCENT, 1.0, 2))
story.append(p(
    "The user's original request contained 10 checklist items framed for Shopify/WooCommerce. The "
    "table below maps each item to its equivalent concern in the actual Next.js stack and gives the "
    "current status. Detailed findings for each failed item appear in Sections 5–8."
))

checklist_rows = [
    ["1", "HTTPS / SSL enforced site-wide", "Caddy TLS termination + HSTS header in next.config.ts",
     Paragraph('<font color="#B91C1C"><b>FAIL</b></font> — no HSTS, no security headers at all (H-4)', S_TABLE_CELL)],
    ["2", "Audit installed plugins/apps", "npm dependencies + custom API routes",
     Paragraph('<font color="#B91C1C"><b>FAIL</b></font> — unused deps, no rate limit, no validation (H-1, H-2, L-6/7/8)', S_TABLE_CELL)],
    ["3", "Two-factor auth on admin accounts", "No User model exists; next-auth declared but unused",
     Paragraph('<font color="#B91C1C"><b>FAIL</b></font> — no auth system whatsoever (C-1, M-7)', S_TABLE_CELL)],
    ["4", "Daily off-site backups + restore test", "SQLite file + cron + S3 sync",
     Paragraph('<font color="#B91C1C"><b>FAIL</b></font> — no backups configured anywhere (Deployment section)', S_TABLE_CELL)],
    ["5", "Review user roles / remove admin access", "Prisma User model + role middleware",
     Paragraph('<font color="#B91C1C"><b>FAIL</b></font> — no users, no roles, no admin panel (M-7)', S_TABLE_CELL)],
    ["6", "Rate-limiting / brute-force protection", "Middleware or Upstash Ratelimit on routes",
     Paragraph('<font color="#B91C1C"><b>FAIL</b></font> — zero rate limiting; no middleware.ts (H-2)', S_TABLE_CELL)],
    ["7", "Scan for malware / injected code", "Repo scan of src/ + public/",
     Paragraph('<font color="#CA8A04"><b>PARTIAL</b></font> — no malware found, but Caddyfile SSRF (C-8) is worse', S_TABLE_CELL)],
    ["8", "PCI-compliant payment provider", "eSewa + Khalti are PCI-compliant gateways",
     Paragraph('<font color="#EA580C"><b>AT RISK</b></font> — gateways OK, but no callback verification (C-2, C-3, C-4)', S_TABLE_CELL)],
    ["9", "Activity logging for admin actions", "AuditLog Prisma model + middleware",
     Paragraph('<font color="#B91C1C"><b>FAIL</b></font> — no audit log; Prisma logs PII to stdout (H-8, M-7)', S_TABLE_CELL)],
    ["10", "Written incident-response plan", "This report, Section 11",
     Paragraph('<font color="#15803D"><b>PROVIDED</b></font> — see Section 11 of this report', S_TABLE_CELL)],
]
story.append(make_table(
    ["#", "Original Checklist Item", "Next.js Stack Equivalent", "Status"],
    checklist_rows,
    col_widths=[10*mm, 50*mm, 55*mm, 65*mm]
))
story.append(Spacer(1, 8))
story.append(p(
    "<b>Translation principle.</b> Three of the original items (HTTPS, plugin audit, brute-force "
    "protection) translate almost directly: HTTPS becomes Caddy TLS plus HSTS in Next.js config; "
    "the plugin audit becomes an npm dependency review; brute-force protection becomes rate-limiting "
    "middleware. Three items (2FA, user roles, activity logging) cannot be addressed at all in the "
    "current build because the application has no concept of a user account — there is no User model, "
    "no login form, no session cookie. These items require adding NextAuth plus a Prisma User and "
    "AuditLog model before they can even be evaluated. The remaining items (backups, malware scan, "
    "PCI compliance, IR plan) are operational rather than code-level and are addressed in Sections "
    "11 and 12."
))

story.append(PageBreak())

# ---------------- Section 6: Critical Findings ----------------
story.append(p("5. Critical Findings (8)", S_H1))
story.append(hr(C_ACCENT, 1.0, 2))
story.append(p(
    "Critical findings represent issues that allow direct compromise of customer data, direct "
    "financial loss, or remote code execution. Each must be closed before any production deployment. "
    "Estimated remediation effort for all 8 Critical findings: approximately 6–10 hours of developer "
    "time."
))

# C-1
story.extend(finding_block(
    "C-1", "CRITICAL",
    "Unauthenticated GET /api/bookings leaks customer PII",
    "src/app/api/bookings/route.ts:43-57",
    "The GET handler returns the 50 most recent bookings to any caller with no authentication, no "
    "API key check, no origin check, and no auth header verification. A grep across the entire "
    "<font name='LibMono'>src/</font> tree confirms zero matches for <font name='LibMono'>"
    "getServerSession</font>, <font name='LibMono'>signIn</font>, <font name='LibMono'>next-auth</font>, "
    "or <font name='LibMono'>requireAuth</font> — authentication has never been wired up anywhere in "
    "the application.",
    "Any anonymous internet user can run <font name='LibMono'>curl https://&lt;prod-domain&gt;/api/bookings</font> "
    "and immediately receive a JSON array containing real customer names, email addresses, phone "
    "numbers, requested service types, wedding dates, and free-text messages. This is a direct "
    "violation of the Nepal Privacy Act 2075 and would constitute a notifiable data breach under "
    "GDPR if any European data subjects have submitted bookings. The same exposure applies to any "
    "future GET endpoint added to /api/contact or /api/payment.",
    fix_code=(
        "// Option A: delete the GET handler entirely if not needed.\n"
        "// Option B: gate behind NextAuth admin session.\n"
        "import { getServerSession } from 'next-auth';\n"
        "import { authOptions } from '@/lib/auth';\n\n"
        "export async function GET(req: NextRequest) {\n"
        "  const session = await getServerSession(authOptions);\n"
        "  if (!session || session.user.role !== 'ADMIN') {\n"
        "    return NextResponse.json({}, { status: 401 });\n"
        "  }\n"
        "  const bookings = await db.booking.findMany({\n"
        "    orderBy: { createdAt: 'desc' },\n"
        "    take: 50,\n"
        "  });\n"
        "  return NextResponse.json({ success: true, bookings });\n"
        "}"
    ),
    fix_text="Remove the GET handler, or require an authenticated admin session before returning any "
             "data. The next-auth dependency is already declared in package.json — it just needs to "
             "be configured (see M-7 for the User and AuditLog schema additions)."
))

# C-2
story.extend(finding_block(
    "C-2", "CRITICAL",
    "Payment callback routes do not exist — no signature verification, orders never marked paid",
    "src/app/api/payment/esewa/initiate/route.ts:83-84, src/app/api/payment/khalti/initiate/route.ts:70",
    "Both payment initiation routes configure success/failure callback URLs pointing to "
    "<font name='LibMono'>/api/payment/esewa/callback</font> and "
    "<font name='LibMono'>/api/payment/khalti/callback</font>, but no such route files exist. "
    "A filesystem search under <font name='LibMono'>src/app/api/</font> returns only "
    "<font name='LibMono'>bookings</font>, <font name='LibMono'>contact</font>, "
    "<font name='LibMono'>payment/esewa/initiate</font>, and "
    "<font name='LibMono'>payment/khalti/initiate</font> — no callback directories.",
    "In production, after a customer completes payment, eSewa redirects their browser to the callback "
    "URL with a base64-encoded data payload and an HMAC-SHA256 signature. That URL currently returns "
    "a 404, so the customer sees a broken page immediately after paying. Worse, the PaymentOrder row "
    "in the database is never updated from <i>initiated</i> to <i>paid</i> — the studio has no "
    "automated record that payment occurred. Even if a callback route is later added without proper "
    "verification, an attacker could forge a callback request and mark any order paid, because the "
    "eSewa HMAC signature is currently never checked server-side. Khalti has the same gap: its "
    "server-to-server lookup verification step is also missing.",
    fix_code=(
        "// src/app/api/payment/esewa/callback/route.ts\n"
        "import crypto from 'crypto';\n"
        "import { db } from '@/lib/db';\n\n"
        "export async function POST(req: NextRequest) {\n"
        "  const form = await req.formData();\n"
        "  const data = String(form.get('data') || '');\n"
        "  const signature = String(form.get('signature') || '');\n"
        "  const signedFieldNames = String(form.get('signed_field_names') || '');\n\n"
        "  // Re-derive the signature from the returned fields in the order eSewa specifies.\n"
        "  const fields = signedFieldNames.split(',').map(f => `${f}=${form.get(f)}`).join(',');\n"
        "  const expected = crypto\n"
        "    .createHmac('sha256', process.env.ESEWA_SECRET_KEY!)\n"
        "    .update(fields)\n"
        "    .digest('base64');\n\n"
        "  // Constant-time comparison to prevent timing attacks.\n"
        "  const a = Buffer.from(signature);\n"
        "  const b = Buffer.from(expected);\n"
        "  if (a.length !== b.length || !crypto.timingSafeEqual(a, b)) {\n"
        "    return NextResponse.json({ error: 'Invalid signature' }, { status: 400 });\n"
        "  }\n\n"
        "  // Decode the data payload, look up the order, mark it paid.\n"
        "  const decoded = JSON.parse(Buffer.from(data, 'base64').toString('utf8'));\n"
        "  await db.paymentOrder.update({\n"
        "    where: { transactionUuid: decoded.transaction_uuid },\n"
        "    data: { status: 'paid', rawResponse: data },\n"
        "  });\n"
        "  return NextResponse.redirect(`${process.env.FRONTEND_URL}/payment/success`);\n"
        "}"
    ),
    fix_text="Implement callback routes for both gateways. For eSewa: verify the HMAC signature "
             "using the secret key, then mark the order paid. For Khalti: call the "
             "/api/v2/epayment/lookup/ endpoint server-side with the pidx to verify status. "
             "Always use crypto.timingSafeEqual for signature comparison to prevent timing attacks."
))

# C-3
story.extend(finding_block(
    "C-3", "CRITICAL",
    "Demo mode silently marks orders as paid without any payment",
    "src/app/api/payment/esewa/initiate/route.ts:45-67, src/app/api/payment/khalti/initiate/route.ts:43-66",
    "When <font name='LibMono'>ESEWA_SECRET_KEY</font> or <font name='LibMono'>KHALTI_SECRET_KEY</font> "
    "is unset, both routes log a warning and then immediately persist a PaymentOrder row with "
    "<font name='LibMono'>status: \"paid\"</font> and <font name='LibMono'>rawResponse: \"demo_mode\"</font>, "
    "returning a success response to the client. The current <font name='LibMono'>.env</font> file "
    "contains only DATABASE_URL — neither secret is set — so the deployed app is currently in demo "
    "mode, meaning every payment is free.",
    "If this build is deployed to production without setting the env vars (and the build script does "
    "not enforce their presence), any visitor can pay NPR 1 for a NPR 14,999 wedding package and "
    "immediately receive a success confirmation, with the database marking the order paid. The studio "
    "would show up to photograph a wedding that was never paid for. Even if the env vars are correctly "
    "set in production, the demo branch remains in the code — any future misconfiguration silently "
    "disables payment enforcement with no error or alarm.",
    fix_code=(
        "// Remove the demo branch entirely. Fail fast in production.\n"
        "// src/lib/env.ts (new file)\n"
        "export function assertProdEnv() {\n"
        "  if (process.env.NODE_ENV !== 'production') return;\n"
        "  const required = [\n"
        "    'DATABASE_URL', 'ESEWA_SECRET_KEY', 'ESEWA_PRODUCT_CODE',\n"
        "    'KHALTI_SECRET_KEY', 'BACKEND_URL', 'FRONTEND_URL', 'NEXTAUTH_SECRET',\n"
        "  ];\n"
        "  for (const k of required) {\n"
        "    if (!process.env[k]) {\n"
        "      throw new Error(`Missing required env var: ${k}`);\n"
        "    }\n"
        "  }\n"
        "}\n\n"
        "// Call assertProdEnv() at the top of every payment route handler."
    ),
    fix_text="Remove the demo branch entirely. If demo mode is needed for local development, gate it "
             "behind NODE_ENV !== 'production' AND an explicit PAYMENT_DEMO_MODE=1 flag, and never "
             "auto-set status to 'paid' — use status: 'demo' instead. At boot, fail-fast if production "
             "env is missing any required secret."
))

# C-4
story.extend(finding_block(
    "C-4", "CRITICAL",
    "Server fully trusts client-supplied payment amount",
    "src/app/api/payment/esewa/initiate/route.ts:18-27, src/app/api/payment/khalti/initiate/route.ts:16-26",
    "Both payment initiation routes read <font name='LibMono'>amount</font> from the JSON request "
    "body and use it directly as the charge amount after only a basic <font name='LibMono'>"
    "Number(amount) &gt; 0</font> check. The server never cross-references the supplied "
    "<font name='LibMono'>packageName</font> against the canonical SERVICES list in "
    "<font name='LibMono'>src/lib/site.ts</font> to verify that the amount matches the actual price.",
    "An attacker can submit a request like <font name='LibMono'>{\"amount\":1, \"packageName\":"
    "\"Wedding Photography\", \"customerName\":\"x\", \"customerPhone\":\"x\"}</font> and pay NPR 1 "
    "for a NPR 14,999 wedding package. In production with real eSewa, the customer is charged NPR 1 "
    "and the studio is contractually on the hook for a wedding. In demo mode (the current state of "
    "the deployed app), the order is marked paid for NPR 1. The same attack applies to Khalti.",
    fix_code=(
        "// Look up the package server-side; ignore client-supplied amount.\n"
        "import { SERVICES } from '@/lib/site';\n\n"
        "export async function POST(req: NextRequest) {\n"
        "  const { packageKey, customerName, customerPhone } = await req.json();\n"
        "  const pkg = SERVICES.find(s => s.key === packageKey);\n"
        "  if (!pkg) {\n"
        "    return NextResponse.json({ error: 'Unknown package' }, { status: 400 });\n"
        "  }\n"
        "  const totalAmount = String(pkg.priceFrom); // server-side canonical price\n"
        "  // ... proceed with eSewa/Khalti initiation using totalAmount\n"
        "}"
    ),
    fix_text="Never trust client-supplied payment amounts. The server should look up the package by "
             "a stable key (not by name) and use the canonical price from the server-side SERVICES "
             "constant. Optionally also enforce idempotency tokens so the amount can't change between "
             "quote and charge."
))

# C-5
story.extend(finding_block(
    "C-5", "CRITICAL",
    "SQLite database with customer PII committed to git",
    "db/custom.db (binary file, tracked since initial commit 2a64e5d)",
    "The SQLite database file <font name='LibMono'>db/custom.db</font> is tracked in git. Running "
    "<font name='LibMono'>strings db/custom.db | head -80</font> reveals real-looking PII: names, "
    "emails, phone numbers, transaction UUIDs, and payment statuses. The .gitignore rule for "
    "<font name='LibMono'>*.log</font> and <font name='LibMono'>.env*</font> does not retroactively "
    "untrack files that were committed before the rule was added.",
    "Anyone with read access to the repository — future contributors, anyone a remote is pushed to, "
    "anyone who purchases the source code from a contractor — has the full customer PII dataset, "
    "forever, in git history. Even if the current data is test data, the schema is designed to hold "
    "real customer PII, and the workflow commits the DB on every change. If real customer data is "
    "ever added and pushed, it cannot be removed without rewriting git history and force-pushing "
    "every remote.",
    fix_code=(
        "# 1. Stop tracking the file (keeps local copy).\n"
        "git rm --cached db/custom.db\n\n"
        "# 2. Add to .gitignore (explicit, not wildcard).\n"
        "echo 'db/*.db' >> .gitignore\n"
        "echo 'db/*.db-journal' >> .gitignore\n\n"
        "# 3. Purge ALL historical copies from every commit.\n"
        "git filter-repo --path db/custom.db --invert-paths\n"
        "# (or use BFG Repo-Cleaner: java -jar bfg.jar --delete-files custom.db)\n\n"
        "# 4. Force-push to overwrite every remote.\n"
        "git push origin --force --all\n"
        "git push origin --force --tags\n\n"
        "# 5. Rotate any real PII that was committed. Notify affected customers\n"
        "#    if these are real bookings (required under Nepal Privacy Act 2075)."
    ),
    fix_text="Remove the file from tracking, add an explicit gitignore rule, purge history with "
             "git filter-repo or BFG, force-push all remotes, and notify any affected customers. "
             "For production, point DATABASE_URL at a path outside the repo (e.g. "
             "/var/lib/wedding-moment-nepal/custom.db)."
))

# C-6
story.extend(finding_block(
    "C-6", "CRITICAL",
    ".env file committed to git",
    ".env (currently 1 line: DATABASE_URL=...), tracked since initial commit",
    "The <font name='LibMono'>.env</font> file is tracked in git. It currently contains only "
    "DATABASE_URL, but the .gitignore pattern <font name='LibMono'>.env*</font> was added after "
    "the file was already committed, so it remains tracked. The pattern of committing .env is "
    "already established; the moment anyone adds ESEWA_SECRET_KEY, KHALTI_SECRET_KEY, or "
    "NEXTAUTH_SECRET to the file, those secrets ship to the repo.",
    "This is a near-certain future secret leak. The eSewa and Khalti secret keys control real "
    "money movement — anyone with the eSewa product code and secret could forge payment "
    "confirmations for the studio's account. The NEXTAUTH_SECRET controls session token signing, "
    "and its leak would allow an attacker to forge admin sessions. The current state (only "
    "DATABASE_URL exposed) is a warning shot, not a stable situation.",
    fix_code=(
        "# 1. Stop tracking .env.\n"
        "git rm --cached .env\n\n"
        "# 2. Be explicit in .gitignore (don't rely on wildcard).\n"
        "echo '.env' >> .gitignore\n"
        "echo '.env.local' >> .gitignore\n"
        "echo '.env.production' >> .gitignore\n\n"
        "# 3. Purge from history.\n"
        "git filter-repo --path .env --invert-paths\n"
        "git push origin --force --all\n\n"
        "# 4. Create .env.example (committed) with placeholder values:\n"
        "#    DATABASE_URL=file:./db/custom.db\n"
        "#    ESEWA_SECRET_KEY=your_esewa_secret_here\n"
        "#    ESEWA_PRODUCT_CODE=your_merchant_code\n"
        "#    KHALTI_SECRET_KEY=your_khalti_secret_here\n"
        "#    BACKEND_URL=https://weddingmomentnepal.com\n"
        "#    FRONTEND_URL=https://weddingmomentnepal.com\n"
        "#    NEXTAUTH_SECRET=run `openssl rand -base64 32`\n"
        "#    NEXTAUTH_URL=https://weddingmomentnepal.com"
    ),
    fix_text="Untrack .env, add explicit gitignore rules, purge history, force-push. Use a secrets "
             "manager (Doppler, Vault, AWS SSM) or at minimum an untracked .env.local for development. "
             "Document required env vars in a committed .env.example that contains no real values."
))

# C-7
story.extend(finding_block(
    "C-7", "CRITICAL",
    "Build script ships the dev database to production",
    ".zscripts/build.sh:143-156",
    "The build script explicitly copies the development SQLite database (the same one committed to "
    "git, containing test entries) into the production build tarball, then runs "
    "<font name='LibMono'>prisma db push --accept-data-loss</font> against the copy. The comment "
    "in the script reads <i>\"将测试环境数据库复制到构建产物中，生产环境直接使用这份数据库\"</i> "
    "(\"Copy the test environment database to the build artifact; production uses this database "
    "directly\").",
    "Production customers see a database pre-populated with dev test data (Sujan Dai, Jane Smith, "
    "Test User, etc.). When production starts writing real bookings, those real bookings layer on "
    "top of test data, mixing real and fake PII. Additionally, <font name='LibMono'>db push "
    "--accept-data-loss</font> is destructive — if the schema has changed since the dev DB was "
    "created, columns may be dropped silently during build, losing data without warning. The "
    "deployed production environment starts in a known-bad state.",
    fix_code=(
        "# In .zscripts/build.sh — REPLACE the database copy block:\n\n"
        "# OLD (delete this):\n"
        "# if [ -f './db/custom.db' ]; then\n"
        "#     mkdir -p \"$BUILD_DIR/db\"\n"
        "#     cp -r ./db/. \"$BUILD_DIR/db/\"\n"
        "#     DATABASE_URL=\"file:$BUILD_DIR/db/custom.db\" bun run db:push\n"
        "# fi\n\n"
        "# NEW: create an empty production database with the current schema.\n"
        "mkdir -p \"$BUILD_DIR/db\"\n"
        "DATABASE_URL=\"file:$BUILD_DIR/db/custom.db\" bun run db:push\n"
        "# The production database starts empty. Real data is added by customers."
    ),
    fix_text="Never copy a dev database into production. The build script should create an empty "
             "production DB at build time (prisma db push against a fresh file, no cp). Better: "
             "production should not ship with a DB file at all — DATABASE_URL should point at a "
             "managed Postgres or a persistent volume mounted at runtime."
))

# C-8
story.extend(finding_block(
    "C-8", "CRITICAL",
    "Caddyfile has unauthenticated SSRF via XTransformPort query parameter",
    "Caddyfile:2-13",
    "The production Caddyfile contains a route that reads <font name='LibMono'>XTransformPort</font> "
    "from the query string and reverse-proxies the request to <font name='LibMono'>"
    "localhost:{query.XTransformPort}</font>. There is no allowlist, no authentication, no validation. "
    "Any external request to <font name='LibMono'>http://&lt;host&gt;:81/?XTransformPort=&lt;port&gt;</font> "
    "causes Caddy to open a connection to that localhost port and pipe the response back.",
    "This is a textbook server-side request forgery (SSRF) and proxy bypass. An attacker can probe "
    "every port on localhost (1 through 65535) to map internal services; reach internal-only admin "
    "panels, metrics endpoints (Prometheus on :9090), Docker socket proxies, Redis (:6379), Postgres "
    "(:5432), cloud metadata services; and bounce requests through Caddy to disguise their origin. "
    "The Caddyfile is committed to git and loaded by <font name='LibMono'>.zscripts/start.sh:145</font> "
    "as the production proxy. This vulnerability is remotely exploitable by anyone who can reach the "
    "server.",
    fix_code=(
        "# Caddyfile — DELETE this entire block:\n"
        "@transform_port_query {\n"
        "    query XTransformPort=*\n"
        "}\n"
        "handle @transform_port_query {\n"
        "    reverse_proxy localhost:{query.XTransformPort} {\n"
        "        header_up Host {host}\n"
        "    }\n"
        "}\n\n"
        "# If port transformation is genuinely needed (it appears to be a sandbox\n"
        "# debugging aid), bind to 127.0.0.1 only and require an HMAC-signed token:\n"
        "# @allowed_port {\n"
        "#     query XTransformPort=3000\n"
        "#     expression {http.request.header.X-Debug-Token} eq \"{env.DEBUG_TOKEN}\"\n"
        "# }"
    ),
    fix_text="Remove the @transform_port_query block entirely. If port transformation is genuinely "
             "needed (it appears to be a sandbox debugging aid), bind to 127.0.0.1 only and require "
             "an HMAC-signed token. At minimum, restrict to a known allowlist of ports."
))

story.append(PageBreak())

# ---------------- Section 7: High Findings ----------------
story.append(p("6. High Findings (9)", S_H1))
story.append(hr(C_ACCENT, 1.0, 2))
story.append(p(
    "High findings represent issues that materially weaken the security posture but are not "
    "individually exploitable to the point of immediate compromise. They should be closed within "
    "the first week of remediation work."
))

story.extend(finding_block(
    "H-1", "HIGH",
    "No input validation framework — Zod installed but unused",
    "All four API routes (bookings/route.ts:9-16, contact/route.ts:9-16, esewa/initiate/route.ts:18-25, khalti/initiate/route.ts:16-23)",
    "The package.json declares <font name='LibMono'>zod@^4.0.2</font>, but no route imports it. "
    "Validation is ad-hoc: <font name='LibMono'>if (!name || !email || !phone || !service || !date)</font>, "
    "followed by <font name='LibMono'>String(name)</font> coercion. No email format check, no phone "
    "normalization, no length cap, no service enum validation, no date parsing.",
    "A booking with <font name='LibMono'>email: \"not-an-email\"</font>, "
    "<font name='LibMono'>phone: \"&lt;script&gt;alert(1)&lt;/script&gt;\"</font>, "
    "<font name='LibMono'>service: \"anything-not-in-our-list\"</font>, "
    "<font name='LibMono'>date: \"1900-13-99\"</font>, or "
    "<font name='LibMono'>message: &lt;10 MB string&gt;</font> is accepted and persisted. "
    "<font name='LibMono'>String(name)</font> on an object produces <i>\"[object Object]\"</i>. "
    "A 10 MB message will be written to SQLite, allowing trivial database bloat DoS. If any future "
    "admin UI renders the message field without escaping, it becomes a stored XSS.",
    fix_code=(
        "import { z } from 'zod';\n\n"
        "const BookingSchema = z.object({\n"
        "  name: z.string().min(2).max(100),\n"
        "  email: z.string().email().max(255),\n"
        "  phone: z.string().regex(/^\\+?[\\d\\s-]{6,20}$/),\n"
        "  service: z.enum(['portrait','wedding','commercial','event']),\n"
        "  date: z.string().regex(/^\\d{4}-\\d{2}-\\d{2}$/)\n"
        "    .refine(s => new Date(s) > new Date(), 'Date must be in the future'),\n"
        "  message: z.string().max(5000).optional(),\n"
        "});\n\n"
        "export async function POST(req: NextRequest) {\n"
        "  const parsed = BookingSchema.safeParse(await req.json());\n"
        "  if (!parsed.success) {\n"
        "    return NextResponse.json({ errors: parsed.error.flatten() }, { status: 422 });\n"
        "  }\n"
        "  const booking = await db.booking.create({ data: parsed.data });\n"
        "  // ...\n"
        "}"
    )
))

story.extend(finding_block(
    "H-2", "HIGH",
    "No rate limiting anywhere",
    "Confirmed by grep — zero matches for 'rate.?limit|RateLimit|throttle' in src/. No middleware.ts exists.",
    "Every API route accepts unlimited requests from any origin. No in-memory token bucket, no "
    "Redis-backed limiter, no per-IP throttling. There is no <font name='LibMono'>middleware.ts</font> "
    "file at all — the project has never had any request-level middleware.",
    "<font name='LibMono'>/api/bookings</font> and <font name='LibMono'>/api/contact</font> create "
    "a DB row on every POST. An attacker can fill the SQLite file to disk in seconds — each row is "
    "small but the message field is uncapped (see H-1), so 1 MB per row × 1000 requests per second = "
    "approximately 1 GB per minute. The payment initiation routes create PaymentOrder rows on every "
    "POST; an attacker can flood the orders table with millions of rows, breaking any future "
    "reconciliation. In production mode, each initiate also calls out to the upstream gateway, so "
    "an attacker can exhaust the Khalti API rate limit and get the studio's merchant account throttled.",
    fix_code=(
        "// Install: bun add @upstash/ratelimit @upstash/redis\n"
        "import { Ratelimit } from '@upstash/ratelimit';\n"
        "import { Redis } from '@upstash/redis';\n\n"
        "const limiter = new Ratelimit({\n"
        "  redis: Redis.fromEnv(),\n"
        "  limiter: Ratelimit.slidingWindow(5, '1 m'), // 5 req/min per IP\n"
        "});\n\n"
        "export async function POST(req: NextRequest) {\n"
        "  const ip = req.headers.get('x-forwarded-for')?.split(',')[0] ?? 'anon';\n"
        "  const { success } = await limiter.limit(ip);\n"
        "  if (!success) {\n"
        "    return NextResponse.json({ error: 'Too many requests' }, { status: 429 });\n"
        "  }\n"
        "  // ... proceed with handler\n"
        "}"
    ),
    fix_text="Install @upstash/ratelimit + @upstash/redis (or use Vercel KV). Wrap each route with "
             "a 5-req-per-minute-per-IP limit. For form spam, also add Cloudflare Turnstile on the "
             "booking and contact forms."
))

story.extend(finding_block(
    "H-3", "HIGH",
    "No CSRF protection on POST routes",
    "All POST handlers in bookings/route.ts:6, contact/route.ts:6, esewa/initiate/route.ts:16, khalti/initiate/route.ts:16",
    "These are raw <font name='LibMono'>route.ts</font> handlers (not Next.js Server Actions, which "
    "have built-in CSRF). They accept <font name='LibMono'>Content-Type: application/json</font> from "
    "any origin. No Origin/Referer check, no CSRF token.",
    "Today, since there is no auth (see C-1), the worst an attacker can do is flood the DB (covered "
    "by H-2). But the moment admin auth is added, any logged-in admin visiting an attacker-controlled "
    "page can be CSRF-tricked into creating bookings, deleting data, or initiating refunds. The "
    "pattern is set up wrong from day one.",
    fix_code=(
        "// Add Origin check at the top of every POST handler.\n"
        "const ALLOWED_ORIGINS = new Set([\n"
        "  'https://weddingmomentnepal.com',\n"
        "  'http://localhost:3000',\n"
        "]);\n\n"
        "export async function POST(req: NextRequest) {\n"
        "  const origin = req.headers.get('origin');\n"
        "  if (!origin || !ALLOWED_ORIGINS.has(origin)) {\n"
        "    return NextResponse.json({ error: 'Forbidden origin' }, { status: 403 });\n"
        "  }\n"
        "  // ... proceed with handler\n"
        "}"
    ),
    fix_text="Either (a) convert handlers to Next.js Server Actions (which auto-emit CSRF tokens), "
             "or (b) add an Origin check plus a double-submit cookie or JWT-bound CSRF token for "
             "auth'd routes."
))

story.extend(finding_block(
    "H-4", "HIGH",
    "No security headers (CSP, HSTS, X-Frame-Options, etc.)",
    "next.config.ts:1-12 (the entire file — no headers() function)",
    "The Next.js config sets only <font name='LibMono'>output: \"standalone\"</font>, "
    "<font name='LibMono'>typescript.ignoreBuildErrors: true</font>, and "
    "<font name='LibMono'>reactStrictMode: false</font>. No security headers are configured anywhere "
    "— not in next.config.ts, not in middleware.ts (which doesn't exist), not in the Caddyfile.",
    "Without CSP, any future stored XSS (e.g., booking message rendered without escaping) executes "
    "unrestricted and can steal data or make authenticated requests. Without "
    "<font name='LibMono'>X-Frame-Options: DENY</font>, the site can be clickjacked — an attacker "
    "overlays the booking form on top of a fake \"Win a free wedding!\" button. Without HSTS, a "
    "man-in-the-middle on HTTP can downgrade a customer mid-session. Without "
    "<font name='LibMono'>X-Content-Type-Options: nosniff</font>, uploaded files can be MIME-sniffed "
    "into executable types.",
    fix_code=(
        "// next.config.ts — add a headers() function:\n"
        "const nextConfig = {\n"
        "  output: 'standalone',\n"
        "  poweredByHeader: false, // also fixes H-5\n"
        "  reactStrictMode: true,  // also fixes H-6\n"
        "  typescript: { ignoreBuildErrors: false }, // also fixes H-6\n"
        "  async headers() {\n"
        "    return [{\n"
        "      source: '/(.*)',\n"
        "      headers: [\n"
        "        { key: 'Content-Security-Policy',\n"
        "          value: \"default-src 'self'; img-src 'self' data:; \" +\n"
        "                 \"style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; \" +\n"
        "                 \"font-src 'self' https://fonts.gstatic.com; \" +\n"
        "                 \"script-src 'self'; frame-ancestors 'none'; \" +\n"
        "                 \"base-uri 'self'; form-action 'self'; upgrade-insecure-requests\" },\n"
        "        { key: 'Strict-Transport-Security',\n"
        "          value: 'max-age=63072000; includeSubDomains; preload' },\n"
        "        { key: 'X-Frame-Options', value: 'DENY' },\n"
        "        { key: 'X-Content-Type-Options', value: 'nosniff' },\n"
        "        { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },\n"
        "        { key: 'Permissions-Policy', value: 'geolocation=(), microphone=(), camera=()' },\n"
        "      ],\n"
        "    }];\n"
        "  },\n"
        "};"
    )
))

story.extend(finding_block(
    "H-5", "HIGH",
    "X-Powered-By header not disabled — framework version leaked",
    "next.config.ts:1-12",
    "Next.js by default sends <font name='LibMono'>X-Powered-By: Next.js</font> on every response. "
    "Bun may add its own header. The config does not set "
    "<font name='LibMono'>poweredByHeader: false</font>.",
    "Allows attackers to fingerprint the stack instantly and target known Next.js CVEs (the 14.x "
    "and 15.x lines have had several SSRF and cache-poisoning advisories). Combined with the "
    "committed package.json, attackers can confirm the exact patch level and look up matching "
    "exploits.",
    fix_text="Add <font name='LibMono'>poweredByHeader: false</font> to nextConfig in next.config.ts "
             "(shown in the H-4 fix). Also strip the header at Caddy as a defense-in-depth measure."
))

story.extend(finding_block(
    "H-6", "HIGH",
    "typescript.ignoreBuildErrors: true and reactStrictMode: false",
    "next.config.ts:6-9",
    "Type errors don't block production builds — a route could ship with a typo'd field name "
    "(<font name='LibMono'>booking.emial</font> instead of <font name='LibMono'>booking.email</font>) "
    "and silently write <font name='LibMono'>undefined</font> to the database. Strict mode is off, "
    "disabling React's double-effect safety check that catches impure renders leaking data between "
    "concurrent users (e.g., a stale closure leaking one user's session into another's render).",
    "Type errors in production code can cause silent data corruption — the most insidious bug class "
    "because nothing crashes, but the wrong data is persisted. React strict mode catches impure "
    "effects that leak data between users; without it, a coding mistake could expose one customer's "
    "booking data to another customer.",
    fix_text="Set <font name='LibMono'>ignoreBuildErrors: false</font> and "
             "<font name='LibMono'>reactStrictMode: true</font> in next.config.ts (shown in the H-4 "
             "fix). Fix any resulting type errors before deploying — they are real bugs hiding "
             "behind the silence flag."
))

story.extend(finding_block(
    "H-7", "HIGH",
    "Khalti route leaks upstream error response to client",
    "src/app/api/payment/khalti/initiate/route.ts:97-102",
    "When Khalti's initiate API returns a non-OK response, the route returns "
    "<font name='LibMono'>{ success: false, message: 'Khalti initiation failed', details: data }</font> "
    "with status 502, where <font name='LibMono'>data</font> is the full Khalti API error response.",
    "Khalti's error responses may include merchant ID, internal request IDs, validation details, or "
    "partial credential echoes — useful reconnaissance for an attacker probing the integration. "
    "Additionally, returning 502 to the client leaves the PaymentOrder row in <i>initiated</i> status "
    "forever, polluting the database with orders that never resolved.",
    fix_code=(
        "// Log full error server-side; return generic message to client.\n"
        "if (!resp.ok) {\n"
        "  console.error('[Khalti] initiate failed:', data);\n"
        "  // Mark the order as failed so it doesn't linger in 'initiated'.\n"
        "  await db.paymentOrder.update({\n"
        "    where: { purchaseOrderId },\n"
        "    data: { status: 'failed', rawResponse: JSON.stringify(data) },\n"
        "  });\n"
        "  return NextResponse.json(\n"
        "    { success: false, message: 'Payment gateway unavailable' },\n"
        "    { status: 502 }\n"
        "  );\n"
        "}"
    )
))

story.extend(finding_block(
    "H-8", "HIGH",
    "Prisma client logs all queries including parameter values",
    "src/lib/db.ts:9-11",
    "<font name='LibMono'>new PrismaClient({ log: ['query'] })</font> emits every SQL statement "
    "with bound parameter values to stdout. Every email, phone number, and message string is "
    "printed to stdout on every request that touches the database.",
    "The start script (<font name='LibMono'>package.json:8</font>) tees server output to "
    "<font name='LibMono'>server.log</font> in the project root, so all PII lands in a file in the "
    "working directory. The dev script does the same with <font name='LibMono'>dev.log</font>. "
    "Both files contain raw PII. If <font name='LibMono'>NODE_ENV</font> is unset (misconfigured "
    "production), the query logger also runs in production. Log aggregation services (Datadog, "
    "Sentry) may ingest and retain this indefinitely.",
    fix_code=(
        "// src/lib/db.ts — only enable query logging in dev.\n"
        "import { PrismaClient } from '@prisma/client';\n\n"
        "const log = process.env.NODE_ENV === 'development'\n"
        "  ? ['query', 'error', 'warn']\n"
        "  : ['error', 'warn'];\n\n"
        "export const db = new PrismaClient({ log });"
    ),
    fix_text="Enable query logging only in development. For production, use ['warn', 'error'] only "
             "and rely on application-level structured logging when query tracing is needed."
))

story.extend(finding_block(
    "H-9", "HIGH",
    "start script tees everything to server.log in working directory",
    "package.json:8",
    "<font name='LibMono'>\"start\": \"NODE_ENV=production bun .next/standalone/server.js 2&gt;&amp;1 "
    "| tee server.log\"</font> writes all server output (errors, stack traces, Prisma query logs "
    "if H-8 isn't fixed, any console.log from a route that prints an email) to "
    "<font name='LibMono'>server.log</font> in the project root.",
    "The file persists, is not rotated, is world-readable by default, and on a containerized deploy "
    "comes along for the ride in the image layer. <font name='LibMono'>server.log</font> is in "
    ".gitignore (so it won't be committed), but the runtime exposure remains: anyone with shell "
    "access to the container can read it.",
    fix_text="Send logs to stdout only — let the container runtime or systemd journald capture "
             "them. Or write to a properly-permissioned /var/log/wedding-moment-nepal/server.log "
             "with logrotate. Never write logs inside the app working directory."
))

story.append(PageBreak())

# ---------------- Section 8: Medium Findings ----------------
story.append(p("7. Medium Findings (14)", S_H1))
story.append(hr(C_ACCENT, 1.0, 2))
story.append(p(
    "Medium findings are real issues that increase risk or maintainability burden but are not "
    "immediately exploitable in isolation. They should be addressed within the first month."
))

medium_data = [
    ("M-1", "Predictable eSewa transactionUuid (Math.random, 1000 suffixes per ms)",
     "<font name='LibMono'>src/app/api/payment/esewa/initiate/route.ts:28</font>",
     "Use <font name='LibMono'>crypto.randomUUID()</font>: "
     "<font name='LibMono'>const transactionUuid = `order-${crypto.randomUUID()}`;</font>"),
    ("M-2", "Khalti purchaseOrderId is even more predictable (no random suffix)",
     "<font name='LibMono'>src/app/api/payment/khalti/initiate/route.ts:27</font>",
     "Same fix as M-1: use crypto.randomUUID()."),
    ("M-3", "No honeypot / captcha on any form",
     "<font name='LibMono'>src/components/site/{booking,contact,payment}.tsx</font>",
     "Add Cloudflare Turnstile (free, privacy-respecting) to each form. Verify server-side before "
     "persisting. Also add a honeypot field (hidden input named 'website') and reject submissions "
     "where it's filled."),
    ("M-4", "Booking date field is a raw string with no server-side validation",
     "<font name='LibMono'>src/app/api/bookings/route.ts:11, :24</font>",
     "Parse with <font name='LibMono'>z.string().date()</font> (ISO 8601) and "
     "<font name='LibMono'>.refine(s =&gt; new Date(s) &gt; new Date(), 'Date must be in the future')</font>."),
    ("M-5", "Khalti customer_info.email hardcoded to customer@example.com",
     "<font name='LibMono'>src/app/api/payment/khalti/initiate/route.ts:77</font>",
     "Collect email in payment.tsx and pass it through. Validate with Zod. Khalti sends receipts to "
     "this address — currently the studio gets nothing and the customer gets nothing."),
    ("M-6", "amount stored as Float in Prisma schema",
     "<font name='LibMono'>prisma/schema.prisma:30</font>",
     "Change to <font name='LibMono'>amount Decimal @db.Decimal(10, 2)</font>. Floats cannot "
     "represent currency exactly; round-off bugs accumulate over time and break reconciliation."),
    ("M-7", "No AuditLog model — no trail of admin actions or payment transitions",
     "<font name='LibMono'>prisma/schema.prisma:1-47</font>",
     "Add User, AuditLog, and WebhookEvent models (see code block below). Required for PCI-DSS "
     "audit trail and Nepal Privacy Act 2075 data subject access requests."),
    ("M-8", "No soft-delete or data retention policy",
     "<font name='LibMono'>prisma/schema.prisma:11-46 (no deletedAt columns)</font>",
     "Add <font name='LibMono'>deletedAt DateTime?</font> to each model. Use Prisma soft-delete "
     "middleware or explicit <font name='LibMono'>where: { deletedAt: null }</font> filters. Add a "
     "cron job to hard-delete rows older than N years."),
    ("M-9", "BACKEND_URL and FRONTEND_URL default to empty string — silent breakage",
     "<font name='LibMono'>src/app/api/payment/esewa/initiate/route.ts:30, khalti/initiate/route.ts:44-45</font>",
     "Fail-fast at boot if these are unset in production. See the assertProdEnv() helper in the C-3 fix."),
    ("M-10", "ESEWA_PRODUCT_CODE defaults to EPAYTEST (eSewa sandbox)",
     "<font name='LibMono'>src/app/api/payment/esewa/initiate/route.ts:29</font>",
     "Require the env var in production. Never default to a sandbox code. Same fail-fast pattern as M-9."),
    ("M-11", "String(name) accepts objects and arrays — no schema coercion",
     "<font name='LibMono'>src/app/api/bookings/route.ts:20-25, contact/route.ts:20-23</font>",
     "Use Zod (H-1) — it rejects non-string inputs before they reach String() coercion. "
     "<font name='LibMono'>String({foo: 'bar'})</font> produces <i>\"[object Object]\"</i>."),
    ("M-12", "No request body size limit on POST routes",
     "All POST handlers (<font name='LibMono'>await req.json()</font> with no size check)",
     "Read the body with a size cap: <font name='LibMono'>const text = await req.text(); if "
     "(text.length &gt; 50_000) return NextResponse.json({error:'Body too large'}, {status: 413}); "
     "const body = JSON.parse(text);</font>"),
    ("M-13", "rawResponse: 'demo_mode' is a confusing sentinel",
     "<font name='LibMono'>src/app/api/payment/esewa/initiate/route.ts:55, khalti/initiate/route.ts:54</font>",
     "Use a structured value: <font name='LibMono'>rawResponse: JSON.stringify({ demo: true, ts: "
     "Date.now() })</font>. Or add a <font name='LibMono'>demo Boolean @default(false)</font> column."),
    ("M-14", "Production runs on Bun runtime",
     "<font name='LibMono'>package.json:8, .zscripts/start.sh:93</font>",
     "Switch to <font name='LibMono'>node .next/standalone/server.js</font>. Pin Node 20 LTS or "
     "newer. Bun is less battle-tested for production HTTP serving and has had HTTP smuggling "
     "advisories in early versions."),
]

for fid, title, file_line, fix in medium_data:
    title_table = Table([[
        severity_badge("MEDIUM"),
        Paragraph(f'<b>{fid}.</b> {title}', S_FINDING_TITLE)
    ]], colWidths=[70, 110])
    title_table.setStyle(TableStyle([
        ("VALIGN", (0,0), (-1,-1), "TOP"),
        ("LEFTPADDING", (0,0), (-1,-1), 0),
        ("RIGHTPADDING", (0,0), (-1,-1), 0),
        ("TOPPADDING", (0,0), (-1,-1), 0),
        ("BOTTOMPADDING", (0,0), (-1,-1), 0),
    ]))
    story.append(title_table)
    story.append(Paragraph(f'<font name="LibMono" size="8.5" color="#64748B">{file_line}</font>', S_FINDING_META))
    story.append(Paragraph(fix, S_FINDING_BODY))
    story.append(Spacer(1, 4))

# Add the M-7 model schema as a code block since it's referenced
story.append(Paragraph("<b>M-7 detail: Add these models to prisma/schema.prisma</b>", S_FINDING_LABEL))
story.append(code_block(
    "model User {\n"
    "  id           String   @id @default(cuid())\n"
    "  email        String   @unique\n"
    "  passwordHash String\n"
    "  role         String   @default('admin') // admin | staff\n"
    "  twoFactorEnabled Boolean @default(false)\n"
    "  twoFactorSecret String?\n"
    "  createdAt    DateTime @default(now())\n"
    "}\n\n"
    "model AuditLog {\n"
    "  id         String   @id @default(cuid())\n"
    "  actorId    String?\n"
    "  action     String   // e.g. 'login', 'booking.update', 'payment.refund'\n"
    "  entityType String   // 'booking' | 'payment' | 'user' | 'contact'\n"
    "  entityId   String?\n"
    "  metadata   String?  // JSON string\n"
    "  ip         String?\n"
    "  userAgent  String?\n"
    "  createdAt  DateTime @default(now())\n"
    "}\n\n"
    "model WebhookEvent {\n"
    "  id         String   @id @default(cuid())\n"
    "  gateway    String   // 'esewa' | 'khalti'\n"
    "  eventType  String\n"
    "  payload    String   // raw body\n"
    "  signature  String?\n"
    "  verified   Boolean  @default(false)\n"
    "  createdAt  DateTime @default(now())\n"
    "}"
))

story.append(PageBreak())

# ---------------- Section 9: Low / Informational Findings ----------------
story.append(p("8. Low & Informational Findings (19)", S_H1))
story.append(hr(C_ACCENT, 1.0, 2))
story.append(p(
    "Low and Informational findings are cleanup, hygiene, and defense-in-depth items. None is "
    "individually exploitable to a serious outcome, but they collectively indicate an immature "
    "security posture and should be addressed during normal maintenance."
))

low_rows = [
    ["L-1", "examples/websocket/", "Unused websocket server code shipped in repo", "Remove or move to separate repo"],
    ["L-2", "tool-results/", "HTML dumps of unrelated site committed", "git rm --cached; add to .gitignore"],
    ["L-3", "upload/", "World-writable (0777) dir with source archives", "chmod 755; remove archives; add to .gitignore"],
    ["L-4", ".zscripts/dev.pid", "Dev server PID file committed", "git rm --cached; add *.pid to .gitignore"],
    ["L-5", "skills/", "200+ MB of unrelated ClawHub skills in project root", "Move outside project root"],
    ["L-6", "package.json:61", "next-auth@4.x unused; carries CVE-2024-4068", "Either implement auth (M-7) or remove"],
    ["L-7", "package.json:62", "next-intl unused", "Remove"],
    ["L-8", "package.json:16-78", "Many unused deps: dnd-kit, mdxeditor, recharts, framer-motion, etc.", "Run depcheck; remove unused"],
    ["L-9", "src/components/ui/chart.tsx:83", "dangerouslySetInnerHTML (unused component, dev-only config)", "No action unless wired to user input"],
    ["L-10", "public/robots.txt", "Allows all crawlers; combined with C-1, PII could be indexed", "Add Disallow: /api/ (also fix C-1)"],
    ["L-11", "eslint.config.mjs:10-44", "All safety rules disabled (no-debugger, no-undef, etc.)", "Re-enable rules; fix resulting warnings"],
    ["L-12", ".zscripts/start.sh", "NEXT_TELEMETRY_DISABLED only set in build, not in start", "Export in start.sh too, or set in .env"],
    ["L-13", "prisma/schema.prisma:14-15, :28", "Email/phone plaintext and unencrypted at rest", "Encrypt PII at app layer with KMS; min 600 perms on DB file"],
    ["L-14", "esewa/initiate/route.ts:71-73", "HMAC key length not validated", "Add: if (typeof key !== 'string' || key.length < 16) throw"],
    ["L-15", "Contact email (gmail.com)", "No SPF/DMARC on contact email; no transport encryption", "Use custom domain email with SPF/DMARC"],
    ["L-16", "dev.log, .zscripts/dev.log", "Runtime logs contain sandbox internal IP", "Ensure excluded from build tarball"],
    ["L-17", "Root directory", "No Dockerfile, no CI, no SBOM generation", "Add multi-stage Dockerfile + bun audit in CI"],
    ["L-18", "package.json:10", "prisma db push --accept-data-loss in script", "Remove --accept-data-loss; switch to prisma migrate"],
    ["L-19", "Caddyfile:1", "Caddy listens on :81 (non-standard)", "Document topology; ensure TLS at outer proxy"],
]
story.append(make_table(
    ["ID", "File", "Issue", "Fix"],
    low_rows,
    col_widths=[12*mm, 38*mm, 60*mm, 60*mm]
))
story.append(Spacer(1, 8))
story.append(p(
    "<b>Which Low findings matter most.</b> L-6 (unused next-auth with a known CSRF bypass CVE) and "
    "L-13 (PII plaintext at rest) deserve early attention — L-6 because the dependency is in the "
    "install graph even though nothing imports it, and L-13 because anyone with filesystem access "
    "to the SQLite file reads every customer's email and phone number directly. L-11 (ESLint rules "
    "disabled) and L-18 (<font name='LibMono'>--accept-data-loss</font> in the db push script) are "
    "operational landmines that will cause silent data loss sooner or later. The rest are cleanup "
    "that can happen during normal maintenance."
))

story.append(PageBreak())

# ---------------- Section 10: Remediation Roadmap ----------------
story.append(p("9. Prioritized Remediation Roadmap", S_H1))
story.append(hr(C_ACCENT, 1.0, 2))
story.append(p(
    "The 50 findings have been organized into four tiers based on severity and dependency. Each "
    "tier should be fully closed and verified before moving to the next."
))

# Tier 1
story.append(p("Tier 1 — Block Production Deployment (Day 0, ~4 hours)", S_H2))
story.append(p(
    "These findings are individually exploitable and have direct customer impact. No production "
    "deployment should occur until every Tier 1 item is closed and re-tested. The total estimated "
    "effort is approximately 4 hours for an experienced Next.js developer."
))
story.append(p(
    "<b>Findings in this tier:</b> C-1 (delete unauthenticated GET /api/bookings), C-5 (purge "
    "SQLite DB from git history), C-6 (purge .env from git history), C-7 (rewrite build script "
    "to not copy dev DB), C-8 (delete Caddy SSRF block).",
    S_BODY
))
story.append(p(
    "<b>Verification:</b> (1) <font name='LibMono'>curl https://yoursite.com/api/bookings</font> "
    "returns 404 or 401; (2) <font name='LibMono'>git log --all --full-history -- db/custom.db</font> "
    "returns empty; (3) <font name='LibMono'>git log --all --full-history -- .env</font> returns "
    "empty; (4) build tarball contains an empty <font name='LibMono'>db/custom.db</font>; (5) "
    "<font name='LibMono'>curl 'https://yoursite.com:81/?XTransformPort=22'</font> returns Caddy's "
    "default 404, not an SSH banner."
))

# Tier 2
story.append(p("Tier 2 — Close Critical Payment & Validation Gaps (Week 1, ~2-3 days)", S_H2))
story.append(p(
    "These findings close the remaining Critical-tier payment issues and add the baseline input "
    "validation, rate limiting, and security headers that every web app needs. Effort: 2-3 days."
))
story.append(p(
    "<b>Findings in this tier:</b> C-2 (implement eSewa and Khalti callback routes with signature "
    "verification), C-3 (remove demo mode, add fail-fast env validation), C-4 (server-side price "
    "lookup), H-1 (add Zod schemas to all routes), H-2 (add Upstash rate limiting), H-3 (add "
    "Origin check), H-4 (add security headers)."
))
story.append(p(
    "<b>Verification:</b> (1) end-to-end test payment with eSewa sandbox — order row transitions "
    "from <i>initiated</i> to <i>paid</i> only after the customer actually pays; (2) attempting to "
    "submit a booking with <font name='LibMono'>email: \"not-an-email\"</font> returns 422 with "
    "validation errors; (3) sending 10 requests in 1 minute to <font name='LibMono'>/api/bookings</font> "
    "from the same IP returns 429 on the 6th; (4) browser DevTools shows Content-Security-Policy, "
    "Strict-Transport-Security, X-Frame-Options headers on every response."
))

# Tier 3
story.append(p("Tier 3 — Add Auth, Audit Log, and Polish (Week 2-3, ~1 week)", S_H2))
story.append(p(
    "These findings add the user authentication system, audit logging, and the remaining High-tier "
    "fixes. This tier requires the most new code — adding NextAuth configuration, a User model, an "
    "AuditLog model, and wiring up admin routes. Effort: approximately 1 week."
))
story.append(p(
    "<b>Findings in this tier:</b> M-7 (User, AuditLog, WebhookEvent Prisma models + NextAuth "
    "configuration), H-5 (disable X-Powered-By), H-6 (re-enable TypeScript checks and React strict "
    "mode), H-7 (sanitize Khalti error responses), H-8 (restrict Prisma query logging to dev), "
    "H-9 (remove server.log tee), M-1, M-2 (use crypto.randomUUID for order IDs), M-5 (collect "
    "customer email in payment flow), M-6 (Decimal instead of Float for amounts)."
))
story.append(p(
    "<b>Verification:</b> (1) admin login flow works with 2FA enabled; (2) every admin action "
    "(login, booking update, payment refund) creates an AuditLog row; (3) X-Powered-By header "
    "absent from all responses; (4) running <font name='LibMono'>bun run build</font> with a "
    "deliberate type error fails the build; (5) <font name='LibMono'>server.log</font> is not "
    "created in the working directory."
))

# Tier 4
story.append(p("Tier 4 — Hygiene and Cleanup (Month 2, ongoing)", S_H2))
story.append(p(
    "All remaining Medium and Low findings. These are quality-of-life improvements that harden the "
    "codebase but don't block any specific feature. Schedule them as a dedicated cleanup sprint or "
    "address opportunistically during related work."
))
story.append(p(
    "<b>Findings in this tier:</b> all remaining M-3, M-4, M-8 through M-14, and all L-1 through "
    "L-19. Priority within this tier: L-6 (remove unused next-auth or implement it), L-13 (encrypt "
    "PII at rest), L-11 (re-enable ESLint rules), L-18 (switch from db push to migrate)."
))

story.append(PageBreak())

# ---------------- Section 11: Incident Response Plan ----------------
story.append(p("10. Incident Response Plan", S_H1))
story.append(hr(C_ACCENT, 1.0, 2))
story.append(p(
    "This section addresses the user's checklist item #10: a written incident-response plan with "
    "concrete steps to take if a breach or data loss occurs. The plan follows the standard SANS/NIST "
    "six-phase lifecycle (Preparation → Identification → Containment → Eradication → Recovery → "
    "Lessons Learned) adapted to a small e-commerce storefront operated by a photography studio."
))

story.append(p("Phase 1 — Preparation (do this now, before any incident)", S_H2))
story.append(p(
    "Designate an Incident Response Lead (default: the studio owner). Compile a contact list with "
    "the following entries and store both a digital copy (in a password manager) and a printed copy "
    "off-site. Enable Sentry error tracking (free tier covers a small storefront). Configure "
    "automated daily off-site backups of <font name='LibMono'>db/custom.db</font> to an S3-compatible "
    "bucket with a 30-day retention. Test a restore once per quarter. Pre-draft the customer "
    "notification email template (below) so it can be sent within hours rather than days."
))

story.append(p("Contact List Template", S_H3))
contact_rows = [
    ["Studio Owner / IR Lead", "【Owner name】", "【Phone】, 【Email】", "Decision authority"],
    ["Hosting Provider Support", "【Provider name】", "【Support phone/ticket URL】", "Server access, snapshots"],
    ["eSewa Merchant Support", "eSewa", "merchantsupport@esewa.com.np, 9801-571111", "Pause/inspect payments"],
    ["Khalti Merchant Support", "Khalti", "merchantcare@khalti.com, 9801-671111", "Pause/inspect payments"],
    ["Nepal Cyber Bureau", "Nepal Police", "cyberbureau@nepalpolice.gov.np, 01-4215100", "Report cybercrime"],
    ["Legal Counsel", "【Lawyer name】", "【Phone】, 【Email】", "Breach notification law"],
    ["PR / Communications", "【Name or agency】", "【Phone】, 【Email】", "Customer comms"],
    ["Insurance Broker", "【Broker name】", "【Phone】, 【Email】", "Cyber-liability claim"],
]
story.append(make_table(
    ["Role", "Organization", "Contact", "Purpose"],
    contact_rows,
    col_widths=[35*mm, 30*mm, 50*mm, 45*mm]
))

story.append(p("Phase 2 — Identification (the first hour)", S_H2))
story.append(p(
    "Trigger an investigation if any of these occur: Sentry reports a spike in 5xx errors or a "
    "specific payment-related error; a customer reports they were charged but saw no confirmation; "
    "the studio receives a booking or payment that doesn't match customer communication; an unfamiliar "
    "IP appears in access logs hitting <font name='LibMono'>/api/*</font> routes repeatedly; the "
    "database file grows unusually fast (sign of H-2 attack). Begin a written incident log immediately "
    "— timestamp every observation, decision, and action. Assign the incident a severity using the "
    "matrix below."
))

story.append(p("Severity Matrix", S_H3))
sev_rows = [
    ["SEV-1 Critical", "Confirmed PII exfiltration OR forged payments OR DB deletion", "All-hands response, invoke Phase 3 immediately"],
    ["SEV-2 High", "Suspected breach, gateway abuse, or sustained DDoS", "IR Lead convenes within 1 hour"],
    ["SEV-3 Medium", "Single customer impact, isolated bug, no PII exposure", "Resolve within 1 business day"],
    ["SEV-4 Low", "Cosmetic issue, near-miss, hardening opportunity", "Track and batch-resolve"],
]
story.append(make_table(
    ["Severity", "Trigger Examples", "Response SLA"],
    sev_rows,
    col_widths=[30*mm, 80*mm, 60*mm]
))

story.append(p("Phase 3 — Containment (first 60 minutes of a confirmed SEV-1/SEV-2)", S_H2))
story.append(p(
    "Take the site offline immediately by stopping Caddy: <font name='LibMono'>caddy stop</font> "
    "(or <font name='LibMono'>systemctl stop caddy</font>). Snapshot the current database file "
    "before any changes: <font name='LibMono'>cp db/custom.db /tmp/incident-$(date +%s).db</font>. "
    "Preserve all logs: <font name='LibMono'>journalctl -u caddy --since '24 hours ago' &gt; /tmp/"
    "incident-caddy.log</font> and copy <font name='LibMono'>server.log</font> to a secure location. "
    "Rotate all secrets immediately: eSewa secret key, Khalti secret key, NEXTAUTH_SECRET, any DB "
    "credentials. Disable the affected payment gateway in the eSewa/Khalti merchant dashboards "
    "until eradication is complete. Notify the IR Lead and legal counsel — do NOT notify customers "
    "yet (that's Phase 5)."
))

story.append(p("Phase 4 — Eradication (hours to days)", S_H2))
story.append(p(
    "Identify the root cause by correlating logs with the findings in this audit report. Most likely "
    "scenarios given the current codebase: (a) the Caddy SSRF (C-8) was used to reach an internal "
    "service; (b) the unauthenticated GET /api/bookings (C-1) was scraped; (c) a forged payment "
    "callback (C-2) marked orders paid without payment; (d) the demo-mode (C-3) was triggered by "
    "an env var being unset. Patch the specific vulnerability using the fix code in this report. "
    "Re-deploy from a clean build (after Tier 1 of the remediation roadmap is complete). Verify "
    "the fix with the test in the relevant finding's 'Suggested fix' section. Do not bring the site "
    "back online until the root cause is patched and verified."
))

story.append(p("Phase 5 — Recovery and Notification", S_H2))
story.append(p(
    "Restore the database from the most recent clean backup if data was modified. Bring the site "
    "back online behind a fresh Caddy config and rotated secrets. Monitor Sentry and access logs "
    "for 72 hours for re-infection or follow-on attacks. Notify affected customers within 72 hours "
    "of confirmation (Nepal Privacy Act 2075 requires notification; GDPR requires 72 hours if any "
    "EU data subjects are involved). Use the template below. Notify eSewa and Khalti merchant "
    "support if payment data was involved. Notify the Nepal Cyber Bureau if the incident involves "
    "active attack rather than misconfiguration. Notify your cyber-liability insurer within the "
    "policy's reporting window."
))

story.append(p("Customer Notification Email Template", S_H3))
story.append(code_block(
    "Subject: Security Incident Affecting Your Wedding Moment Nepal Account\n\n"
    "Dear 【Customer Name】,\n\n"
    "We are writing to inform you of a security incident that may have affected your\n"
    "personal information. On 【date】, we discovered that 【brief description of incident,\n"
    "e.g., 'an unauthorized party accessed our booking database']. Based on our investigation,\n"
    "the following information of yours may have been exposed: 【list specific fields —\n"
    "name, email, phone, wedding date, etc.】.\n\n"
    "We have taken the following steps: 【list actions — site taken offline, vulnerability\n"
    "patched, secrets rotated, etc.】. We recommend that you: 【list customer actions —\n"
    "change password if you have an account, be alert for phishing, etc.】.\n\n"
    "We deeply regret this incident and have implemented additional controls to prevent\n"
    "recurrence. If you have questions, please reply to this email or call 【studio phone】.\n\n"
    "Sincerely,\n"
    "【Owner name】\n"
    "Wedding Moment Nepal"
))

story.append(p("Phase 6 — Post-Mortem (within 7 days of recovery)", S_H2))
story.append(p(
    "Within 7 days of returning to normal operations, complete a written post-mortem covering: "
    "(1) timeline of the incident from first detection to recovery; (2) root cause analysis — "
    "which finding in this audit report was exploited, and why wasn't it closed; (3) what worked "
    "and what didn't in the IR process; (4) specific action items with owners and due dates to "
    "prevent recurrence. Share the post-mortem with the IR Lead, legal counsel, and any affected "
    "team members. Update this incident-response plan based on lessons learned. File the post-mortem "
    "with the incident log for future reference and for any regulatory audit."
))

story.append(PageBreak())

# ---------------- Section 12: Deployment Hardening Checklist ----------------
story.append(p("11. Deployment Hardening Checklist", S_H1))
story.append(hr(C_ACCENT, 1.0, 2))
story.append(p(
    "Operational hardening that should be in place before the site accepts real customer payments. "
    "Each area has a brief explanation and a checklist of concrete items."
))

story.append(p("Environment Variables", S_H2))
story.append(p(
    "All secrets must be set in the production environment before the application boots. The "
    "assertProdEnv() helper (see C-3 fix) should fail-fast at startup if any required variable is "
    "missing. Never ship secrets in the git repo or in the build tarball."
))
story.append(p(
    "[ ] <font name='LibMono'>DATABASE_URL</font> points to a path outside the repo<br/>"
    "[ ] <font name='LibMono'>ESEWA_SECRET_KEY</font> set (production value, not EPAYTEST)<br/>"
    "[ ] <font name='LibMono'>ESEWA_PRODUCT_CODE</font> set (production merchant code)<br/>"
    "[ ] <font name='LibMono'>KHALTI_SECRET_KEY</font> set (production live key)<br/>"
    "[ ] <font name='LibMono'>BACKEND_URL</font> = <font name='LibMono'>https://weddingmomentnepal.com</font><br/>"
    "[ ] <font name='LibMono'>FRONTEND_URL</font> = <font name='LibMono'>https://weddingmomentnepal.com</font><br/>"
    "[ ] <font name='LibMono'>NEXTAUTH_SECRET</font> = output of <font name='LibMono'>openssl rand -base64 32</font><br/>"
    "[ ] <font name='LibMono'>NEXTAUTH_URL</font> = <font name='LibMono'>https://weddingmomentnepal.com</font><br/>"
    "[ ] <font name='LibMono'>UPSTASH_REDIS_REST_URL</font> and <font name='LibMono'>UPSTASH_REDIS_REST_TOKEN</font> for rate limiting<br/>"
    "[ ] <font name='LibMono'>SENTRY_DSN</font> for error tracking<br/>"
    "[ ] <font name='LibMono'>NODE_ENV</font> = <font name='LibMono'>production</font>",
    S_BODY_TIGHT
))

story.append(p("Backups", S_H2))
story.append(p(
    "Automated daily off-site backups of the SQLite database, with monthly restore tests. Backups "
    "must be encrypted at rest in the off-site location and access-controlled. A backup that has "
    "never been restored is not a backup — it's a hope."
))
story.append(p(
    "[ ] Daily cron job: <font name='LibMono'>sqlite3 db/custom.db '.backup /tmp/backup.db'</font> then "
    "upload to S3-compatible storage<br/>"
    "[ ] Backup retention: 30 days daily, 12 months monthly<br/>"
    "[ ] Backups encrypted with AES-256 (S3 server-side encryption or GPG)<br/>"
    "[ ] Restore test: monthly, restore to a staging DB and run a query<br/>"
    "[ ] Off-site: backups stored in a different region/account than production<br/>"
    "[ ] Access: backup bucket is read-only for the production IAM user<br/>"
    "[ ] Documented: restore procedure is written down and tested by a second person",
    S_BODY_TIGHT
))

story.append(p("Monitoring", S_H2))
story.append(p(
    "Three layers of monitoring: errors (Sentry), access logs (Better Stack or Logtail), and "
    "transactional email (Postmark or Resend) so the studio knows when bookings/payments occur even "
    "if they don't check the admin panel."
))
story.append(p(
    "[ ] Sentry: <font name='LibMono'>@sentry/nextjs</font> installed and configured; DSN in env<br/>"
    "[ ] Sentry alert on any 5xx error in production<br/>"
    "[ ] Access logs: Caddy access log shipped to log aggregator<br/>"
    "[ ] Alert on &gt;100 requests/min from a single IP<br/>"
    "[ ] Alert on any POST to <font name='LibMono'>/api/payment/*/callback</font> with invalid signature<br/>"
    "[ ] Transactional email: new booking, new contact, new payment — email to studio<br/>"
    "[ ] Uptime monitor: external ping every 5 minutes; alert on 3 consecutive failures",
    S_BODY_TIGHT
))

story.append(p("Dependency Updates", S_H2))
story.append(p(
    "Next.js has had multiple CVEs in 14.x and 15.x (cache poisoning, SSRF, prototype pollution). "
    "Establish a monthly cadence for reviewing and applying updates."
))
story.append(p(
    "[ ] Weekly: <font name='LibMono'>bun audit</font> in CI; fail build on high or critical<br/>"
    "[ ] Monthly: review and apply non-security updates<br/>"
    "[ ] Next.js patch releases: upgrade within 7 days of release<br/>"
    "[ ] Next.js minor releases: upgrade within 30 days<br/>"
    "[ ] Subscribe to the Next.js security advisory RSS feed<br/>"
    "[ ] Subscribe to Prisma security advisories<br/>"
    "[ ] Quarterly: run <font name='LibMono'>depcheck</font> and remove unused dependencies",
    S_BODY_TIGHT
))

story.append(PageBreak())

# ---------------- Appendix A ----------------
story.append(p("Appendix A — Shopify / WooCommerce Mapping", S_H1))
story.append(hr(C_ACCENT, 1.0, 2))
story.append(p(
    "The user's original request was framed for a Shopify or WooCommerce store. This appendix maps "
    "every finding in this report to its equivalent on Shopify and WooCommerce, in case the studio "
    "ever migrates platforms. The takeaway: Shopify handles items 1, 4, and 8 essentially for free "
    "(TLS, backups, PCI compliance are built-in); WooCommerce handles them with configuration and "
    "plugins. The remaining items (2FA, rate limiting, audit logging, incident response) require "
    "configuration on both platforms but are easier on Shopify because the admin surface is smaller."
))

map_rows = [
    ["1", "HTTPS / TLS", "Automatic on all plans; HSTS managed by Shopify", "Requires Let's Encrypt + really-simple-ssl plugin"],
    ["2", "Plugin/app audit", "Apps installed via Shopify App Store; review in Admin → Apps", "Plugins via WP admin; use Wordfence Scan"],
    ["3", "2FA on admin", "Enable in Settings → Users → Two-step authentication", "Use Wordfence Login Security or 2FA plugin"],
    ["4", "Daily backups", "Automatic; export via Admin → Products → Export", "Use UpdraftPlus or Jetpack Backup"],
    ["5", "User roles", "Staff accounts with granular permissions; default roles limited", "WordPress roles: Subscriber → Super Admin; use Members plugin to customize"],
    ["6", "Rate limiting", "Built-in at edge; no configuration needed", "Use Wordfence or Cloudflare WAF rule"],
    ["7", "Malware scan", "Automatic; Shopify monitors theme files", "Use Wordfence Scan or Sucuri"],
    ["8", "PCI compliance", "Shopify Payments is PCI-DSS Level 1; no card data on your store", "Use Stripe or WooCommerce Payments; never store PANs"],
    ["9", "Activity logging", "Limited in core; use Shopify Audit Log (Shopify Plus) or an app", "Use WP Activity Log or Wordfence Audit"],
    ["10", "Incident-response plan", "Shopify handles infra incidents; you handle store config incidents", "Same IR plan as this report; just for WordPress layer"],
]
story.append(make_table(
    ["#", "Concern", "Shopify Equivalent", "WooCommerce Equivalent"],
    map_rows,
    col_widths=[8*mm, 32*mm, 65*mm, 65*mm]
))
story.append(Spacer(1, 8))
story.append(p(
    "<b>Migration recommendation.</b> If the studio migrates to Shopify, items 1, 4, and 8 are "
    "essentially solved by the platform — TLS is automatic, backups are managed, and Shopify "
    "Payments is PCI-DSS Level 1 certified. Items 2, 3, and 9 need app installs but are "
    "straightforward. Items 5, 6, and 7 still require configuration but are easier because the "
    "attack surface is smaller (Shopify admin vs. WordPress + WooCommerce + plugins). Item 10 "
    "(incident response) still requires the studio's own plan — this report's Section 11 applies "
    "regardless of platform. On WooCommerce, the situation is roughly inverted: the studio gets "
    "more control but inherits responsibility for almost every item on the list."
))
story.append(p(
    "<b>Cost tradeoff.</b> Shopify Basic is approximately USD 39/month plus payment processing "
    "fees. WooCommerce is free but requires hosting (USD 10–30/month for a small VPS), an SSL "
    "certificate (free with Let's Encrypt), backup plugin (USD 0–15/month), security plugin (USD "
    "0–15/month), and the studio's time to maintain updates. For a small photography studio that "
    "does not want to operate infrastructure, Shopify is the lower-risk choice. For a studio that "
    "wants full control and has technical capacity, the current Next.js build (after the fixes in "
    "this report) is also a reasonable choice — but only after the fixes."
))

# ---------------- Appendix B ----------------
story.append(p("Appendix B — Verification Checklist", S_H1))
story.append(hr(C_ACCENT, 1.0, 2))
story.append(p(
    "A printable checklist the studio owner or a security reviewer can use to confirm each fix is "
    "applied. Grouped by finding ID. After all items are checked, complete the Final Go-Live Gate."
))

story.append(p("Critical Findings", S_H2))
story.append(p(
    "[ ] <b>C-1:</b> <font name='LibMono'>curl https://yoursite.com/api/bookings</font> returns 401 or 404<br/>"
    "[ ] <b>C-2:</b> End-to-end sandbox payment transitions order from <i>initiated</i> to <i>paid</i><br/>"
    "[ ] <b>C-2:</b> Forged callback with wrong signature returns 400<br/>"
    "[ ] <b>C-3:</b> <font name='LibMono'>grep -r 'demo_mode' src/</font> returns no matches<br/>"
    "[ ] <b>C-3:</b> Boot fails fast if <font name='LibMono'>ESEWA_SECRET_KEY</font> unset in production<br/>"
    "[ ] <b>C-4:</b> Submitting <font name='LibMono'>{\"amount\":1, \"packageKey\":\"wedding\"}</font> charges NPR 14999<br/>"
    "[ ] <b>C-5:</b> <font name='LibMono'>git log --all -- db/custom.db</font> returns empty<br/>"
    "[ ] <b>C-6:</b> <font name='LibMono'>git log --all -- .env</font> returns empty<br/>"
    "[ ] <b>C-7:</b> Build tarball's <font name='LibMono'>db/custom.db</font> is empty (0 rows in each table)<br/>"
    "[ ] <b>C-8:</b> <font name='LibMono'>curl 'https://yoursite.com:81/?XTransformPort=22'</font> returns 404, not SSH banner",
    S_BODY_TIGHT
))

story.append(p("High Findings", S_H2))
story.append(p(
    "[ ] <b>H-1:</b> Submitting booking with <font name='LibMono'>email: \"not-an-email\"</font> returns 422<br/>"
    "[ ] <b>H-2:</b> 10 POST requests in 1 minute to <font name='LibMono'>/api/bookings</font> returns 429 on 6th<br/>"
    "[ ] <b>H-3:</b> POST from <font name='LibMono'>Origin: https://evil.com</font> returns 403<br/>"
    "[ ] <b>H-4:</b> Response headers include CSP, HSTS, X-Frame-Options, X-Content-Type-Options<br/>"
    "[ ] <b>H-5:</b> <font name='LibMono'>curl -I https://yoursite.com</font> shows no <font name='LibMono'>X-Powered-By</font><br/>"
    "[ ] <b>H-6:</b> <font name='LibMono'>bun run build</font> fails when a type error is introduced<br/>"
    "[ ] <b>H-7:</b> Khalti error response in browser shows generic message, no <font name='LibMono'>details</font> field<br/>"
    "[ ] <b>H-8:</b> Production stdout does not show SQL queries with parameter values<br/>"
    "[ ] <b>H-9:</b> <font name='LibMono'>server.log</font> does not exist in working directory after start",
    S_BODY_TIGHT
))

story.append(p("Medium Findings (spot-check)", S_H2))
story.append(p(
    "[ ] <b>M-1, M-2:</b> <font name='LibMono'>grep 'Math.random' src/app/api/payment/</font> returns empty<br/>"
    "[ ] <b>M-5:</b> Payment form collects email; Khalti receipt goes to customer<br/>"
    "[ ] <b>M-6:</b> <font name='LibMono'>prisma/schema.prisma</font> uses <font name='LibMono'>Decimal @db.Decimal(10, 2)</font><br/>"
    "[ ] <b>M-7:</b> <font name='LibMono'>prisma/schema.prisma</font> has User, AuditLog, WebhookEvent models<br/>"
    "[ ] <b>M-12:</b> POST with 100 KB body returns 413",
    S_BODY_TIGHT
))

story.append(p("Final Go-Live Gate", S_H2))
story.append(p(
    "Before accepting real customer payments, the following five items must all be confirmed. "
    "If any is unchecked, do not go live."
))
story.append(p(
    "[ ] 1. All 8 Critical findings closed and verified per the tests above<br/>"
    "[ ] 2. End-to-end sandbox payment with both eSewa and Khalti succeeds (customer pays, order row transitions to <i>paid</i>, customer sees thank-you page)<br/>"
    "[ ] 3. Daily backup configured and a test restore has been performed successfully<br/>"
    "[ ] 4. Sentry error monitoring is live and receiving events<br/>"
    "[ ] 5. The incident-response plan in Section 11 has been read by the studio owner and the contact list (Section 11, Phase 1) has been filled in",
    S_BODY_TIGHT
))

# ============================================================
# Build the document
# ============================================================
OUTPUT = "/home/z/my-project/download/Wedding_Moment_Nepal_Security_Audit.pdf"

doc = BaseDocTemplate(
    OUTPUT,
    pagesize=A4,
    title="Wedding Moment Nepal — Security Audit Report",
    author="Z.ai Security Review",
    subject="Security audit of Next.js 16 storefront",
    creator="Z.ai",
    leftMargin=20*mm,
    rightMargin=20*mm,
    topMargin=25*mm,
    bottomMargin=22*mm,
)

# Cover frame (full page, no margins)
cover_frame = Frame(0, 0, A4[0], A4[1], leftPadding=0, rightPadding=0,
                    topPadding=0, bottomPadding=0, id='cover')
# Body frame (with margins)
body_frame = Frame(20*mm, 22*mm, A4[0]-40*mm, A4[1]-47*mm,
                   leftPadding=0, rightPadding=0, topPadding=0, bottomPadding=0, id='body')

doc.addPageTemplates([
    PageTemplate(id='cover', frames=[cover_frame], onPage=draw_cover),
    PageTemplate(id='body', frames=[body_frame], onPage=draw_body_page),
])

doc.build(story)
print(f"OK — wrote {OUTPUT}")
print(f"Size: {os.path.getsize(OUTPUT) / 1024:.1f} KB")
